---
abstract: 'RDF model class for Catalyst based on RDF::Trine::Model.'
author:
  - 'Thiago Rondon <thiago@aware.com.br>'
build_requires:
  Catalyst: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-RDF
requires:
  Catalyst::Model: 0
  Moose: 0
  RDF::Trine::Model: 0
resources:
  bugtracker: http://github.com/maluco/Catalyst-Model-RDF/issues
  repository: git://github.com/maluco/Catalyst-Model-RDF
version: 0.01
